<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <title><?php echo isset($this->view['title']) ? $this->view['title'] : 'Midday MVC' ?></title>
</head>
<body>
    <a href="https://github.com/noonie2k/midday-mvc"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>
    <?php echo $this->content(); ?>
</body>
</html>